# Configuration file for pipeline parameters, dataset selection, and experiment settings.
experiment:
  random_state: 42 # For reproducibility of results
  n_iter: 5 # Number of iterations for hyperparameter tuning (e.g., RandomizedSearchCV)
  horizon: 25 # 25 for 1.0s frequency - 1Hz

data:
  datasets: [4, 7, 8, 9, 10, 11, 12, 14, 15, 16, 20, 21, 24, 25] # Datasets to run scripts on
  test_sets: [24, 25] # Datasets to use as test sets, should be a subset of datasets
  flow_rate_missing: [4, 8, 9, 10, 11, 12, 15, 16, 20, 21, 24, 25] # Datasets with missing flow rate data, to be handled accordingly in preprocessing
  target: "Plug_future" # target label
  non_feature_columns: ["Plug_future", "Plug", "LogId"] # Columns that should not be used as features for modeling
  always_keep_columns: ["LogId"] # Columns that should always be retained in the dataset
  LABELED_PATH: "data/labeled/labeled_"
  frequency: 1 # Hz
  required_columns: [
      "Time",
      "LogId",
      "Plug",
      "TS inlet pressure (Mean)",
      "TS outlet pressure (Mean)",
      "Pump outlet pressure (Mean)",
    ] # Required columns for validation of datasets
  numeric_columns: [
      "TS inlet pressure (Mean)",
      "TS outlet pressure (Mean)",
      "Pump outlet pressure (Mean)",
      "Plug",
      "LogId",
    ] # Columns that should contain numeric data, for validation purposes
